In [1]:
import pandas as pd
import numpy as np

## AI Industry Summary CSV Exploration

This CSV contains information on the industry categores (agriculture, education, manufacturing, etc). It explores averages of AI adoption, ai maturity, productivity change, job creation/displacement, customer satisfaction, and AI failure rates. 

float dtype with string for category  
fully non-null

In [8]:
# Import ai industry csv using pandas - it exists one dir up and in Data
check_df_industry = pd.read_csv("../Data/ai_industry_summary.csv")

In [9]:
check_df_industry.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 8 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   industry                         9 non-null      object
 1   avg_ai_adoption_rate             9 non-null      float64
 2   avg_productivity_change_percent  9 non-null      float64
 3   avg_ai_maturity_score            9 non-null      float64
 4   avg_ai_failure_rate              9 non-null      float64
 5   avg_jobs_displaced               9 non-null      float64
 6   avg_jobs_created                 9 non-null      float64
 7   avg_customer_satisfaction        9 non-null      float64
dtypes: float64(7), object(1)
memory usage: 708.0+ bytes

In [10]:
check_df_industry.describe()

,avg_ai_adoption_rate,avg_productivity_change_percent,avg_ai_maturity_score,avg_ai_failure_rate,avg_jobs_displaced,avg_jobs_created,avg_customer_satisfaction
count,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000
mean,36.120000,9.186667,0.341111,25.881111,111.031111,117.026667,5.412222
std,2.657419,0.793048,0.026667,0.963113,10.271640,12.814132,0.090661
min,34.520000,8.600000,0.330000,23.560000,98.440000,107.650000,5.350000
25%,34.700000,8.790000,0.330000,26.130000,106.090000,110.420000,5.370000
50%,35.230000,8.990000,0.330000,26.270000,111.250000,111.100000,5.390000
75%,35.260000,9.130000,0.330000,26.380000,114.990000,116.060000,5.400000
max,42.470000,11.170000,0.410000,26.460000,133.740000,149.080000,5.640000

In [11]:
check_df_industry.shape

(9, 8)

In [12]:
check_df_industry.columns

Index(['industry', 'avg_ai_adoption_rate', 'avg_productivity_change_percent',
       'avg_ai_maturity_score', 'avg_ai_failure_rate', 'avg_jobs_displaced',
       'avg_jobs_created', 'avg_customer_satisfaction'],
      dtype='object')

## AI Company Adoption CSV Exploration

This csv contains company information, survey information, and survey responses. It is the largest data set in the study (150000, 43).

Mix of dtypes object, int, float.  Initial look indicates fully non-null values and  mostly appropriate dtypes.  Explore changing survey_year to date dtype

In [13]:
check_df_company = pd.read_csv("../Data/ai_company_adoption.csv")

In [14]:
check_df_company.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 43 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   response_id                  150000 non-null  int64
 1   company_id                   150000 non-null  object
 2   survey_year                  150000 non-null  int64
 3   quarter                      150000 non-null  object
 4   country                      150000 non-null  object
 5   region                       150000 non-null  object
 6   industry                     150000 non-null  object
 7   company_size                 150000 non-null  object
 8   num_employees                150000 non-null  int64
 9   annual_revenue_usd_millions  150000 non-null  float64
 10  company_founding_year        150000 non-null  int64
 11  company_age                  150000 non-null  int64
 12  company_age_group            150000 non-null  object
 13  ai_adoption_rate             150000 non-null  float64
 14  ai_adoption_stage            150000 non-null  object
 15  years_using_ai               150000 non-null  int64
 16  ai_primary_tool              150000 non-null  object
 17  num_ai_tools_used            150000 non-null  int64
 18  ai_use_case                  150000 non-null  object
 19  ai_projects_active           150000 non-null  int64
 20  ai_training_hours            150000 non-null  float64
 21  ai_budget_percentage         150000 non-null  float64
 22  ai_maturity_score            150000 non-null  float64
 23  ai_failure_rate              150000 non-null  float64
 24  ai_investment_per_employee   150000 non-null  float64
 25  regulatory_compliance_score  150000 non-null  int64
 26  data_privacy_level           150000 non-null  object
 27  ai_ethics_committee          150000 non-null  object
 28  ai_risk_management_score     150000 non-null  int64
 29  remote_work_percentage       150000 non-null  float64
 30  employee_satisfaction_score  150000 non-null  float64
 31  task_automation_rate         150000 non-null  float64
 32  time_saved_per_week          150000 non-null  float64
 33  productivity_change_percent  150000 non-null  float64
 34  jobs_displaced               150000 non-null  int64
 35  jobs_created                 150000 non-null  int64
 36  reskilled_employees          150000 non-null  int64
 37  revenue_growth_percent       150000 non-null  float64
 38  cost_reduction_percent       150000 non-null  float64
 39  innovation_score             150000 non-null  int64
 40  customer_satisfaction        150000 non-null  float64
 41  survey_source                150000 non-null  object
 42  data_collection_method       150000 non-null  object
dtypes: float64(15), int64(14), object(14)
memory usage: 49.2+ MB

In [18]:
check_df_company.shape

(150000, 43)

In [17]:
check_df_company.columns

Index(['response_id', 'company_id', 'survey_year', 'quarter', 'country',
       'region', 'industry', 'company_size', 'num_employees',
       'annual_revenue_usd_millions', 'company_founding_year', 'company_age',
       'company_age_group', 'ai_adoption_rate', 'ai_adoption_stage',
       'years_using_ai', 'ai_primary_tool', 'num_ai_tools_used', 'ai_use_case',
       'ai_projects_active', 'ai_training_hours', 'ai_budget_percentage',
       'ai_maturity_score', 'ai_failure_rate', 'ai_investment_per_employee',
       'regulatory_compliance_score', 'data_privacy_level',
       'ai_ethics_committee', 'ai_risk_management_score',
       'remote_work_percentage', 'employee_satisfaction_score',
       'task_automation_rate', 'time_saved_per_week',
       'productivity_change_percent', 'jobs_displaced', 'jobs_created',
       'reskilled_employees', 'revenue_growth_percent',
       'cost_reduction_percent', 'innovation_score', 'customer_satisfaction',
       'survey_source', 'data_collection_method'],
      dtype='object')

In [19]:
check_df_company.describe()

,response_id,survey_year,num_employees,annual_revenue_usd_millions,company_founding_year,company_age,ai_adoption_rate,years_using_ai,num_ai_tools_used,ai_projects_active,...,task_automation_rate,time_saved_per_week,productivity_change_percent,jobs_displaced,jobs_created,reskilled_employees,revenue_growth_percent,cost_reduction_percent,innovation_score,customer_satisfaction
count,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,...,150000.000000,150000.000000,150000.000000,150000.00000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000
mean,79961.106207,2024.500987,2342.376580,1180.345751,2005.993767,18.507220,36.414726,4.931580,2.315120,6.270693,...,19.761744,6.267406,9.266996,111.36984,117.882507,181.642700,4.606486,4.814909,55.199920,5.420619
std,46158.813039,1.118013,4754.424755,2391.471420,9.473220,9.539367,14.544096,2.429316,0.946826,3.500142,...,9.222562,2.977495,5.637067,255.83778,261.650245,417.929587,5.318773,3.383086,8.593423,1.047142
min,1.000000,2023.000000,10.000000,1.010000,1990.000000,1.000000,0.000000,0.000000,1.000000,0.000000,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,-5.000000,0.000000,40.000000,1.000000
25%,40020.750000,2024.000000,69.000000,33.880000,1998.000000,10.000000,26.430000,3.000000,2.000000,4.000000,...,13.360000,4.180000,5.070000,2.00000,3.000000,3.000000,0.780000,2.120000,49.000000,4.700000
50%,79937.500000,2025.000000,349.000000,184.160000,2006.000000,18.000000,36.320000,5.000000,2.000000,6.000000,...,19.700000,6.230000,9.060000,10.00000,12.000000,16.000000,4.480000,4.620000,55.000000,5.410000
75%,119913.250000,2026.000000,884.000000,444.150000,2014.000000,27.000000,46.200000,7.000000,3.000000,9.000000,...,26.020000,8.290000,13.120000,41.00000,41.000000,64.000000,8.240000,7.130000,61.000000,6.130000
max,160000.000000,2026.000000,19970.000000,9996.730000,2022.000000,36.000000,100.000000,10.000000,6.000000,20.000000,...,59.630000,19.150000,34.360000,2417.00000,1980.000000,3881.000000,30.000000,20.790000,97.000000,9.760000

## Country AI Index CSV Exploration

This dataset explores different countries' stats and ai adoption rates. It specifies country name, continent, gdp, internet, ai maturity rating, researchers, and patent filings.  
The data is a mix of string and float dtypes and has full non-null values.

In [20]:
check_df_industry = pd.read_csv("../Data/country_ai_index.csv")

In [21]:
check_df_industry.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 8 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   country                     30 non-null     object
 1   region                      30 non-null     object
 2   gdp_per_capita              30 non-null     float64
 3   internet_penetration        30 non-null     float64
 4   digital_maturity_index      30 non-null     float64
 5   country_ai_policy           30 non-null     object
 6   ai_patent_filings_2024      30 non-null     int64
 7   ai_researchers_per_million  30 non-null     float64
dtypes: float64(4), int64(1), object(3)
memory usage: 2.0+ KB